name: Build AAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Build AAR
        run: cd smileyrating && gradle assembleRelease

      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: smileyrating-aar
          path: smileyrating/build/outputs/aar/*.aar
