name: Build SmileyRating AAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout SmileyRating repo
      - name: Checkout SmileyRating repo
        uses: actions/checkout@v4
        with:
          repository: sujithkanna/SmileyRating
          path: SmileyRating

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      # Step 3: Install Gradle 7.6
      - name: Install Gradle 7.6
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 7.6

      # Step 4: Patch build.gradle to remove jcenter()
      - name: Replace jcenter() with mavenCentral()
        run: sed -i 's/jcenter()/mavenCentral()/g' SmileyRating/build.gradle

      # Step 5: Remove uploadArchives block
      - name: Remove uploadArchives block
        run: |
          cd SmileyRating
          sed -i '/uploadArchives/{N;N;N;N;N;d;}' smilerating/build.gradle

      # Step 6: Comment out external android-release-aar.gradle
      - name: Comment out external android-release-aar.gradle
        run: |
          cd SmileyRating
          sed -i 's|apply from:.*android-release-aar.gradle|// &|g' smilerating/build.gradle

      # Step 7: Disable Renderscript compilation
      - name: Disable Renderscript
        run: |
          cd SmileyRating
          sed -i '/android {/a \ \ \ \ defaultConfig {\n\ \ \ \ \ \ renderscriptTargetApi 0\n\ \ \ \ \ \ renderscriptSupportModeEnabled false\n\ \ \ \ }' smilerating/build.gradle

      # Step 8: Build AAR ignoring warnings
      - name: Build AAR
        run: |
          cd SmileyRating
          gradle assembleRelease -Dorg.gradle.warning.mode=none

      # Step 9: Upload resulting AAR
      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: smileyrating-aar
          path: SmileyRating/smileyrating/build/outputs/aar/*.aar
